### ISSUE TITLE
Tasks to do

### ISSUE THREAD

**Issue by monoai** [monoai/GDARVR_Fishing#1]
Instead of branching out to multiple issues where some might be too minor/small to be considered as a big issue, our tasks will be collected here instead since this is a small project. If a certain feature/bug is starting to be too big then that will be the time it would be branched out to a separate issue.

For the contributors, feel free to edit this issue and cross out any finished tasks.

# To-do List
**Note:** Assume that the priority of these tasks are from top-to-bottom. It's fine not to be able to do some other tasks as long as the most important tasks contained on the top is achieved. **_Italicized tasks_ are assumed to be intended low priority tasks** and could be skipped temporarily in order to work on the next major task immediately.
## Main Features
These are the features that are intended to be the main basic features of the game in order to be presented as a proof-of-concept. All of the tasks contained here should be done in order to consider the game as completed.

- [x] **Pond can spawn**
  - [x] Once the image marker is scanned, the pond will be able to show up
  - [x] The fishing rod will also show up
  - [x] The reeling button (Button to confirm actions) will show up as well
  - [x] Fish should spawn on start/pond appears
    - [x] At least 2 different fishes should spawn
      - [x] _Fish class should be programmed so that it's easy to have distinct stats (2 different fishes could have different sizes/currency, etc.) for future-proofing_
    - [x] _Fish types should have distinct models_
  - [x] _A main menu/title screen should show up before the pond, rod, and button would show up so that the player would gracefully start the game._
  - [x] _After image target is scanned, implement a way to hide the objects and remind the player to go back to the playing area (image target should be on focus at all times)_
    - Should this be done however? Expectation is that the game should be capable for extended tracking so that it could be flexible on angles, this might make it too stiff and constraining.
- [ ] **Player can use the gyroscope/accelerometer/something to give the controls a motion feel/have a second confirmation action after the reeling button.**
  - [ ] Player moves the phone away from themselves should be casting/placing the bait
  - [ ] Player moves the phone closer to themselves should be reeling/returning the bait
  - To fast track the development, we could temporarily give this capability on a second button, once motion control/gestures are able to be done, we could possibly simply swap the functionality out.
  - Maybe someone could focus on this while the other tasks are being done?
- [x] **Player can cast/place bait on pond**
  - [x] Player should cast a raycast/marker on the pond, signifying where they can place the bait on the pond
    - [x] Visual marker should look like a target or at least a circular transparent marker so it could be accurate
  - [x] Player can hold the reeling button to hold the position of the visual marker indicating where they want to place the bait
    - [x] Releasing the reeling button should unlock the position of the visual marker so the player can reposition
    - [x] _Visual marker should change colors to indicated locked/unlocked position_
  - [x] Player can finalize their choice by doing the motion gesture/pressing temporary dev button
    - [x] The bait should accurately be placed based on where the visual marker is pointing, it should not be placed anywhere else even if the player is looking somewhere else (as long as the reeling button is held).
    - [x] Bait should not move at all and should stay in place
    - [x] Bait should have states readable/accessible by the fish in order to detect if a fish is caught
    - [x] _Player can "undo/reposition" their bait by reeling early without catching any fish. Thus player will go back to casting bait mode immediately._
- [x] **Fish reacts as the bait is placed**
  - [x] Fish can be attracted by the bait
    - [x] Fish should have a *hidden* "attract/interest" meter
      - [x] Interest meter should increase when the bait is placed on the pond
      - [x] Different fishes should have different base interest values
      - [x] _Interest increases differently based on distance_
      - [ ] Interest could be decreased/fish can be scared because of player's early pull out.
    - [x] Fish should move towards the bait if interest is above/equal the threshold
  - [x] Fish can be caught by the bait
    - [x] Only one fish should be caught by the bait, one at a time per se.
    - [x] If a fish is caught, other fishes should stop chasing the bait
    - [x] _Other fishes should return from moving randomly/moves away when another fish gets caught._
  - [x] Fish can be reeled in
    - [x] The reeling button should be held to reel in the fish
      - [x] _Visual indicator that this is the correct way (Button color changes? Visual indicator to motion gesture? Fish temporarily changes color?)_
    - [x] Failure to hold the reeling button should release the fish after 2-4 seconds of idle time
      - [x] Freed fish should scare/move away the fish
        - This can be temporarily teleporting them instantly for now if scare mechanic has not been implemented
      - [x] _Interest should be slightly decreased_
    - [ ] Doing the motion gesture should reel in the fish
      - [ ] Failure to do the motion gesture despite holding the reeling button should release the fish after 4-6 seconds of idle time
        - [x] Freed fish mechanics should be the same as just mentioned earlier.
- [x] **Fish can be be given to player and goes back to bait placement mode**
  - [x] A visual or data indicator should tell the player that they have indeed received the fish
  - [x] Player should go back to casting bait mode after receiving the fish
  - [x] _System/code for this mechanic should be future-proof ready to receive other possible stats (currency, fish data, etc.)_

## Optional Features/Improvements
**Note:** Sections here are labeled differently.

These are the features where our expectation for the main features are high and we managed to easily finish all other features, or maybe we thought that the really base main features are too basic and that we could implement these other stuff anyway, or that it's better to implement them immediately rather than regret cementing spaghetti code, or maybe we just wanted to dream about a really developed concept. Either way, these are the additional/optional features that are a part of the game's concept if it was developed further.

### Animation/Image/Visuals
- [ ] Fishing rod should raise up when the game starts instead of appearing immediately
- [ ] Pond should expand/slowly appear when the game starts instead of appearing immediately
- [ ] Fishing rod should have animations while reeling/casting
- [ ] Fishing rod's fishing line should actually physically move
- [ ] Fishing rod's model should resemble an actual fishing rod
- [ ] Fish and possibly the bait should visually look like they're actually affecting the water (pseudo water-physics or water effects)
- [ ] Bait should look like it caught a fish, possibly by bobbing downwards or an animation indicating something

#### General Gameplay
- [ ] A shop should exist so player can buy more bait types
- [ ] Currency system from catching fishes
- [ ] Better way to handle reeling in order to be fully motion controlled (without relying on reel button)
- [ ] Multiple pond types for exclusive fish types
#### Fish
- [ ] Fish should have Size data
- [ ] Fish should have Currency data
- [ ] Rare fish should exist, which means better price
- [ ] Fish could be attracted easily by certain baits
- [ ] Fish are spawned/despawned by object pooling
#### Bait
- [ ] Different bait types should exist
- [ ] Different reel minigame if the fish has a certain size big enough
  - [ ] Fish would struggle more, have to tap reel button repeatedly, and needs to do one final motion gesture to fish
